### ISSUE TITLE
Add eventhandler option to SUG self-updating

### ISSUE THREAD

**Issue by bduza** [demonnic/MDK#17]
SUG works by running a continuous timer and updating then. Not all information updates work best with a timer though. It may be an option to declare an event for the SUG to listen to and update from that event instead (I'm not sure if this should be an OR or an AND situation?
Example code:
`if self.listento then 
    self.eventhandler = registerAnonymousEventHandler(self.listento,  function()
    --update the gauge here
  end
)
`

**Comment by demonnic** [comment]
* `active = false`
  * will cause it not to run a timer or listen for an event
* `updateTime > 0` 
  * will cause it to not run a timer for the gauge if active.
  * I don't think a repeating tempTimer with a timer of 0 or less is such a great idea anyway
  * I'm lucky I haven't heard about people locking up Mudlet this way
* `updateEvent ~= ""` 
  * will cause it to create an anonymous event handler for updateEvent if active

this is what I think I've settled on.

**Comment by demonnic** [comment]
https://github.com/demonnic/MDK/releases/tag/v2.3.0 =)
