### ISSUE TITLE
TableMaker - optionally make a table with no row divider

### ISSUE THREAD

**Issue by bduza** [demonnic/MDK#18]
Sometimes it would be nice to make a table that has no row divider at all. If I know there will only be a single line of text and I'm trying to fit as much as possible in the vertical space available, then this would be a nice feature.
The attached image is something I produce without using TableMaker (doing so is a headache though!)

![image](https://user-images.githubusercontent.com/36064132/122141467-b6a7e100-ce90-11eb-99c8-15f93e3a4bc7.png)

**Comment by demonnic** [comment]
https://github.com/demonnic/MDK/releases/tag/v2.3.0 has you covered now
