### ISSUE TITLE
Tablemaker - option to truncate/:cut() text when it reaches the column width?

### ISSUE THREAD

**Issue by bduza** [demonnic/MDK#19]
Sometimes using auto wrap isn't ideal. I have gotten around this recently by using :cut() and then setting it as a link that does nothing with clicked, but with the full text displayed in the tooltip.

That's a neat solution for certain types of tables, but I'm wondering if it would be worth building into TableMaker. It may not be! But I'm throwing it out as a possibility (because if I change the column width from 18 to 14, I also need to look for where I am making the text:cut(16) and change it to text:cut(12). Not a major problem as I said, but maybe as an alternate to wrap we could choose autoTruncate or something to that effect?

**Comment by demonnic** [comment]
what about adding a truncate option to fText and having the ability to truncate each column if wrap is false and truncate is true. Then some columns can cause wrapping but others will just truncate. 

not sure how best to handle the 'tooltip' part though, and do I adjust the text to show it's been truncated?

**Comment by demonnic** [comment]
could have an overall tablemaker property which enforces the truncate on each column for you, to avoid having to repeat it each time when you definitely don't want any of that wordwrap business.

**Comment by demonnic** [comment]
Though I did not add any tooltip capability to this, I'm not sure I want to add that automatically, since a whole lot of things would have to be just right for it to happen. Perhaps I'll take a look at adding that in tablemaker itself but going to mark this as addressed in https://github.com/demonnic/MDK/releases/tag/v2.8.4
