### ISSUE TITLE
TextGauge - request reverse fill option.

### ISSUE THREAD

**Issue by Asteria-UI** [demonnic/MDK#29]
Presently gauges fill like this:

:::---50%

It'd be handy if we could have them fill like this:

---:::50%

**Comment by demonnic** [comment]
![image](https://user-images.githubusercontent.com/3660/232320080-0354023c-d745-45af-9ea3-08f875ebfde2.png)

like this?

**Comment by demonnic** [comment]
addressed in https://github.com/demonnic/MDK/releases/tag/v2.8.4
