### ISSUE TITLE
Replace prohibited characters in EMCO tab names when creating filenames

### ISSUE THREAD

**Issue by yetanotherkevin** [demonnic/MDK#39]
While playing with EMCO I had a tab name with a forward slash character in it, e.g. "Say/Shout" and noticed some errors in my output log. It looks like the tab name is used directly as a filename.

https://github.com/demonnic/MDK/blob/main/src/resources/emco.lua#L878

> .../log/anon_window_33/2022/10/02/Say/Shout.html: No such file or directory

Would suggest a quick replacement of `<>:"/\|?*` with underscores or something similar.

**Comment by demonnic** [comment]
This should be resolved with 2.7.1
